Couldinary
hatchways/team-bond pull request #71
Opened 2022-02-12 08:27 UTC by ajkatom

### What this PR does (required):
created controllers for and set up cloudinary
tested with postman but cannot be tested in the app because is depends on profile FE.

2022-02-15 15:14 UTC, moffatethan requested changes
Super close on this one - great work with the cloudinary implementation and attaching profile id to the request object. 

Just two minor comments there then I'll approve.

2022-02-15 15:14 UTC, moffatethan commented on server/models/Profile.js
> +  cloudinary_id: {
Super close on this one - could we just make it camelCase. Everything else looks great! Make sure to change the other files to use `cloudinaryId`

2022-02-15 15:14 UTC, moffatethan commented on server/controllers/profile.js
> +// @route POST /profile//uploadPicture
```suggestion
// @route POST /profile/uploadPicture
```

2022-02-17 19:20 UTC, moffatethan requested changes
Please fix up the merge conflicts then I'll approve 👍🏻

2022-02-17 22:50 UTC, ajkatom commented
> 

done

2022-02-19 01:05 UTC, merged