Payment schema
hatchways/team-bond pull request #73
Opened 2022-02-12 18:55 UTC by ajkatom

### What this PR does (required):
created payment Schema

2022-02-15 21:30 UTC, ezeilo-su reviewed
Good work with this one

2022-02-15 21:30 UTC, ezeilo-su commented on server/utils/stripe.js
> +  console.log(product);
Let's clean up our code and remove this console log.

2022-02-15 21:30 UTC, ezeilo-su commented on server/utils/stripe.js
> +  console.log(plan);
Remove this log too

2022-02-15 21:30 UTC, ezeilo-su commented on server/utils/stripe.js
> +  console.log(subscription);
Please remove

2022-02-17 19:22 UTC, moffatethan approved these changes
Please make sure to base the branches properly, the base branch for this PR should have been the `stripe` branch

2022-02-17 19:22 UTC, moffatethan requested changes
Please fix merge conflict 🙂

2022-02-17 19:59 UTC, merged