Implement FE/profile details page
hatchways/team-bond pull request #85
Opened 2022-02-18 06:20 UTC by esteban-gs

#31 
### What this PR does (required):
- Each Profile will have its own dedicated page that outlines their profile in detail
- Profile id gets passed from query params and fetched on `useEffect`
- Api call for profiles
- Sample data to showcase profile page
- Sample review to showcase reviews list

### Screenshots / Videos (front-end only):
![image](https://user-images.githubusercontent.com/26440947/154628778-2b22e8e8-1103-48d6-84df-4e81bf7259f6.png)

### Any information needed to test this feature (required):
- Post what steps to take to be able to test this feature (eg. "sign up as a new user and upload a profile picture from the navbar")

### Any issues with the current functionality (optional):
- Needs integration with back end

2022-02-18 19:22 UTC, ezeilo-su requested changes
UI looks good! Kindly address those comment that I left here.

2022-02-18 19:22 UTC, ezeilo-su commented on client/src/pages/Profile/ProfileDetail.tsx/ProfileDetail.tsx
> +  }, [id]);
If code is not used please remove it to keep your code clean.

2022-02-18 19:22 UTC, ezeilo-su commented on client/src/pages/Profile/ProfileDetail.tsx/ProfileDetail.tsx
> +                <ProfileReview key={index} review={{ ...item }} />
Using index as a key is an anti-pattern in React and is discouraged. You can use another field for you key.

2022-02-18 19:22 UTC, ezeilo-su commented on client/src/pages/Profile/temp/demo_data.ts
> +// placeholder
Remove comment

2022-02-18 21:10 UTC, moffatethan requested changes
Could we add in the second column with the booking form too? 🙂

2022-02-24 19:35 UTC, moffatethan approved these changes
Great job!!

2022-02-24 21:57 UTC, merged